server:
  port: 8585

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 2240369235@qq.com
    password: rxujblljokcbdijb
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  lance:
    mail:
      sender: 2240369235@qq.com