server:
  port: 8585

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/