server:
  port: 8585

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 2240369235@qq.com
    password: rxujblljokcbdijb
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


##邮箱服务器地址
#spring.mail.protocol=smtp
#spring.mail.host=smtp.qq.com
#  #邮箱服务器地址
#spring.mail.username=************@qq.com
#  #邮箱密码
#spring.mail.password=***********
#spring.mail.default-encoding=UTF-8
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true